# Styling data frames

[Data set download](https://s3.amazonaws.com/bebi103.caltech.edu/data/gfmt_sleep.csv)

<hr>

In [1]:
# Colab setup ------------------
import os, sys, subprocess
if "google.colab" in sys.modules:
    cmd = "pip install --upgrade watermark"
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()
    data_path = "https://s3.amazonaws.com/bebi103.caltech.edu/data/"
else:
    data_path = "../data/"

In [2]:
import pandas as pd

<hr>

It is sometimes useful to highlight features in a data frame when viewing them. (Note that this is generally far less useful than making informative plots, which we will come to shortly.) Pandas offers some convenient ways to style the display of a data frame.

To demonstrate, we will again use a data set from [Beattie, et al.](https://doi.org/10.1098/rsos.160321) containing results from a study the effects of sleep quality on performance in the [Glasgow Facial Matching Test](https://doi.org/10.3758/BRM.42.1.286) (GMFT).

In [3]:
df = pd.read_csv(os.path.join(data_path, 'gfmt_sleep.csv'), na_values='*')

As our first example demonstrating styling, let's say we wanted to highlight rows corresponding to women who scored at or above 75% correct. We can write a function that will take as an argument a row of the data frame, check the value in the `'gender'`  and `'percent correct'` columns, and then specify a row color of gray or green accordingly. We then use `df.style.apply()` with the `axis=1` kwarg to apply that function to each row.

In [4]:
def highlight_high_scoring_females(s):
    if s["gender"] == "f" and s["percent correct"] >= 75:
        return ["background-color: #7fc97f"] * len(s)
    else:
        return ["background-color: lightgray"] * len(s)

df.head(10).style.apply(highlight_high_scoring_females, axis=1)

We can be more fancy. Let's say we want to shade the `'percent correct'` column with a bar corresponding to the value in the column. We use the `df.style.bar()` method to do so. The `subset` kwarg specifies which columns are to have bars.

In [5]:
df.head(10).style.bar(subset=["percent correct"], vmin=0, vmax=100)

Note that I have used the `vmin=0` and `vmax=100` kwargs to set the base of the bar to be at zero and the maximum to be 100.

Alternatively, I could color the percent correct according to the percent correct.

In [6]:
df.head(10).style.background_gradient(subset=["percent correct"], cmap="Reds")

We could have multiple effects together as well.

In [7]:
df.head(10).style.bar(
    subset=["percent correct"], vmin=0, vmax=100
).apply(
    highlight_high_scoring_females, axis=1
)

In practice, I almost never use these features because it is almost always better to display results as a plot rather than in tabular form. Still, it can be useful when exploring data sets to highlight certain aspects when exploring data sets in tabular form.

## Computing environment

In [8]:
%load_ext watermark
%watermark -v -p pandas,jupyterlab

Python implementation: CPython
Python version       : 3.8.11
IPython version      : 7.26.0

pandas    : 1.3.2
jupyterlab: 3.1.7